import { clearContent } from '../../GAS | Library/v02/gas/manualTesting/clearContent';
import { sortColumn } from '../../GAS | Library/v02/gas/manualTesting/sortColumn';
import { paste } from '../../GAS | Library/v02/gas/manualTesting/paste';
import { styleSpreadsheet } from '../../GAS | Library/v02/gas/manualTesting/styleSpreadsheet';
import { styleSheet } from '../../GAS | Library/v02/gas/manualTesting/styleSheet';

// @ts-ignore
global.tests = () => {};

// @ts-ignore
global.menu = {
	clearContent,
	sortColumn,
	paste,
	styleSpreadsheet,
	styleSheet,
};

const menuElements = [
	['clearContent', ['Uruchom test', 'menu.clearContent']],
	'---------------',
	[
		'sortColumn',
		['Kol. A sort A - Z (arkusza a)', 'menu.sortColumn.a1'],
		['Kol. A sort Z - A (arkusza a)', 'menu.sortColumn.a2'],
		['Kol. B sort A - Z (arkusza a)', 'menu.sortColumn.a3'],
		['Kol. B sort Z - A (arkusza a)', 'menu.sortColumn.a4'],
		['Kol. B sort A - Z (arkusza a) (no param)', 'menu.sortColumn.a5'],
		'---------------',
		['Kol. A sort A - Z (arkusza b)', 'menu.sortColumn.b1'],
		['Kol. A sort Z - A (arkusza b)', 'menu.sortColumn.b2'],
		['Kol. B sort A - Z (arkusza b)', 'menu.sortColumn.b3'],
		['Kol. B sort Z - A (arkusza b)', 'menu.sortColumn.b4'],
		'---------------',
		['Kolumna poza zakresem (arkusza a)', 'menu.sortColumn.e1'],
		'---------------',
		['Błędny param (true) (sort) (arkusza a)', 'menu.sortColumn.e2'],
		['Błędny param (dsdsds) (sort) (arkusza a)', 'menu.sortColumn.e3'],
		['Błędny param - "1" - (col) (arkusza a)', 'menu.sortColumn.e4'],
		['Błędny param - A3 - (col) (arkusza a)', 'menu.sortColumn.e5'],
		['Błędny param - A3:B5 - (col) (arkusza a)', 'menu.sortColumn.e6'],
	],
	'---------------',
	[
		'paste (arkusz t01)',
		['Względne - pierwsza kolumna (A)', 'menu.paste.a1'],
		['Względne - środkowa kolumna (B)', 'menu.paste.a2'],
		['Względne - ostatnia kolumna (D)', 'menu.paste.a3'],
		['Względne - kolumny poza zakresem (F)', 'menu.paste.a4'],
		'---',
		['Względne - pierwszy wiersz (1)', 'menu.paste.b1'],
		['Względne - środkowy wiersz (2)', 'menu.paste.b2'],
		['Względne - ostatni wiersz (4)', 'menu.paste.b3'],
		['Względne - wiersza poza zakresem (7)', 'menu.paste.b4'],
		['Względne - wiersz jako string ("1")', 'menu.paste.b5'],
		'---',
		['Bezwzględne do A1', 'menu.paste.c1'],
		['Bezwzględne do B2', 'menu.paste.c2'],
		['Bezwzględne D4', 'menu.paste.c3'],
		['Bezwzględne poza zakresem F6', 'menu.paste.c4'],
		'---',
		['Przekazanie całego zakresu (A1:B2)', 'menu.paste.ea1'],
		['Przekazanie całego zakresu (A1:B)', 'menu.paste.ea2'],
		['Przekazanie całego zakresu (A1:2)', 'menu.paste.ea3'],
	],
	'------------------',
	[
		'paste (arkusz t02)',
		['Względne - pierwsza kolumna (A)', 'menu.paste.d1'],
		['Względne - środkowa kolumna (B)', 'menu.paste.d2'],
		['Względne - ostatnia kolumna (D)', 'menu.paste.d3'],
		['Względne - kolumny poza zakresem (F)', 'menu.paste.d4'],
		'------------------',
		['Względne - pierwszy wiersz (1)', 'menu.paste.e1'],
		['Względne - środkowy wiersz (2)', 'menu.paste.e2'],
		['Względne - ostatni wiersz (4)', 'menu.paste.e3'],
		['Względne - wiersza poza zakresem (7)', 'menu.paste.e4'],
		['Względne - wiersz jako string ("1")', 'menu.paste.e5'],
		'--------------------',
		['Bezwzględne do A1', 'menu.paste.f1'],
		['Bezwzględne do B2', 'menu.paste.f2'],
		['Bezwzględne D4', 'menu.paste.f3'],
		['Bezwzględne poza zakresem F6', 'menu.paste.f4'],
	],
	'------------------',
	[
		'paste (arkusz t03)',
		['Filter on - Wzgl - pierwsza kolumna (A)', 'menu.paste.g1'],
		['Filter on - Wzgl - ostatnia kolumna (E)', 'menu.paste.g2'],
		['Filter on - Wzgl - pierwszy wiersz (1)', 'menu.paste.g3'],
		['Filter on - Wzgl - wiersza poza zakresem (7)', 'menu.paste.g4'],
		['Filter on - Bezwzgl do A1', 'menu.paste.g5'],
		['Filter on - Bezwzgl do F6', 'menu.paste.g6'],
	],
	'------------------',
	[
		'paste (arkusz t04)',
		['Sort 1 - pierwsza kolumna (A)', 'menu.paste.h1'],
		['Sort B - pierwsza kolumna (A)', 'menu.paste.h2'],
		['Sort "A", order "za" - pierwsza kolumna (A)', 'menu.paste.h3'],
		['Sort "B", order "des" - pierwsza kolumna (A)', 'menu.paste.h4'],
	],
	'------------------',
	[
		'paste (arkusz t05)',
		["Clean 'down' - pierwsza kolumna (A)", 'menu.paste.i1'],
		["Clean 'right' - pierwsza kolumna (A)", 'menu.paste.i2'],
		["Clean 'preserve' - pierwsza kolumna (A)", 'menu.paste.i3'],
		["Clean 'down' - drugi wiersz (2)", 'menu.paste.i4'],
		["Clean 'right' - drugi wiersz (2)", 'menu.paste.i5'],
		["Clean 'preserve' - drugi wiersz (2)", 'menu.paste.i6'],
		["Clean 'down' - A3", 'menu.paste.i7'],
		["Clean 'right' - A3", 'menu.paste.i8'],
		["Clean 'preserve' - A3", 'menu.paste.i9'],
	],
	'------------------',
	[
		'paste (arkusz t06)',
		['Nie usuwa empties - pierwsza kolumna (A)', 'menu.paste.j1'],
		['Nie usuwa empties - drugi wiersz (2)', 'menu.paste.j2'],
		['Nie usuwa empties - A3', 'menu.paste.j3'],
	],
	'------------------',
	[
		'styleSpreadsheet',
		['Formatowanie obu arkuszy', 'menu.styleSpreadsheet.a1'],
	],
	'------------------',
	[
		'styleSheet',
		['Ark: "all" - Wszystkie opcje', 'menu.styleSheet.a1'],
		['Ark: "merge" - Wszystkie opcje merge ', 'menu.styleSheet.b1'],
		['Ark: "merge" - Wyłączenie merge ', 'menu.styleSheet.b2'],
		['Ark: "wrap" - Wszystkie opcje', 'menu.styleSheet.c1'],
		['Ark: "fontFormatNum" - Wszystkie opcje', 'menu.styleSheet.d1'],
	],
	'------------------',
	['Test', 'tests'],
	'------------------',
	['Update menu', 'onOpen'],
];

export { menuElements };
